### ISSUE TITLE
DAY 4.2: Deployment Setup (4hrs)

### ISSUE THREAD

**Issue by absolutemadla8** [absolutemadla8/notification-microservice#11]
## Sprint: Day 4 - Deployment
**Assignee**: DevOps Developer  
**Estimate**: 4 hours  
**Priority**: High

### Description
Set up production-ready deployment pipeline and containerization for the notification microservice.

### Tasks
- [ ] Docker optimization for production
- [ ] Docker Compose for production deployment
- [ ] Basic CI/CD script (GitHub Actions)
- [ ] Environment variable documentation
- [ ] Simple deployment script

### Docker Configuration
**Production Dockerfile:**
- Multi-stage build for optimization
- Non-root user for security
- Health checks included
- Minimal image size

**Docker Compose:**
```yaml
version: '3.8'
services:
  notification-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MSG91_API_KEY=${MSG91_API_KEY}
      - MSG91_SENDER_ID=${MSG91_SENDER_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
```

### CI/CD Pipeline
- GitHub Actions workflow
- Automated testing on PR
- Docker image building
- Deployment automation
- Environment promotion

### Deployment Strategy
- Single-command deployment
- Environment variable validation
- Database migration handling
- Service health verification
- Rollback procedures

### Acceptance Criteria
- [ ] Production Docker image optimized and secure
- [ ] Docker Compose ready for production deployment
- [ ] CI/CD pipeline functional
- [ ] Deployment documentation complete
- [ ] Environment variable validation working
- [ ] Health checks properly configured
- [ ] Service can be deployed with single command
